//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorselProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class ders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ders()
        {
            this.ogrenciDers = new HashSet<ogrenciDers>();
        }
    
        public short dersId { get; set; }
        public string dersAd { get; set; }
        public string dersKredi { get; set; }
        public Nullable<short> dersOkulYonetimID { get; set; }
    
        public virtual okulYonetimT okulYonetimT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogrenciDers> ogrenciDers { get; set; }
    }
}
