//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorselProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ogrenci()
        {
            this.ogrenciDers = new HashSet<ogrenciDers>();
        }
    
        public short ogrenciID { get; set; }
        public string ogrenciAdSoyad { get; set; }
        public Nullable<System.DateTime> ogrenciKayitTarih { get; set; }
        public Nullable<System.DateTime> ogrenciDogumTarih { get; set; }
        public string ogrenciBolum { get; set; }
        public string ogrenciNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogrenciDers> ogrenciDers { get; set; }
    }
}
