//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorselProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class okulYonetimT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public okulYonetimT()
        {
            this.ders = new HashSet<ders>();
        }
    
        public short yonetimId { get; set; }
        public string yonetimAdSoyad { get; set; }
        public string yonetimGorevi { get; set; }
        public string yonetimTip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ders> ders { get; set; }
    }
}
